In [5]:
import kagglehub
path1 = kagglehub.dataset_download("ruchikakumbhar/zomato-dataset")

print("Path to dataset files:", path1)

Path to dataset files: C:\Users\jains\.cache\kagglehub\datasets\ruchikakumbhar\zomato-dataset\versions\1

In [6]:
import kagglehub
path2 = kagglehub.dataset_download("sanjay3454chauhan/swiggy-dataset")

print("Path to dataset files:", path2)

Downloading to C:\Users\jains\.cache\kagglehub\datasets\sanjay3454chauhan\swiggy-dataset\1.archive...

100%|██████████| 72.3k/72.3k [00:00<00:00, 244kB/s]

Extracting files...
Path to dataset files: C:\Users\jains\.cache\kagglehub\datasets\sanjay3454chauhan\swiggy-dataset\versions\1

In [7]:
import seaborn as sns
import  matplotlib.pyplot as plt
import pandas as pd

In [15]:
import os

print("ZOMATO files:")
print(os.listdir(path1))

print("\nSWIGGY files:")
print(os.listdir(path2))

import pandas as pd
import os

# Replace the filenames below with whatever Step 1 showed you
zomato = pd.read_csv(os.path.join(path1, 'Zomato-data-.csv'), encoding="latin-1")
swiggy = pd.read_csv(os.path.join(path2, 'swiggy_cleaned.csv'))

print("Zomato:", zomato.shape)
print("Swiggy:", swiggy.shape)

ZOMATO files:
['Zomato-data-.csv']

SWIGGY files:
['swiggy_cleaned.csv', 'swiggy_scrap_uncleaned.csv']
Zomato: (148, 7)
Swiggy: (1749, 7)

In [19]:
swiggy

,hotel_name,rating,time_minutes,food_type,location,offer_above,offer_percentage
0,McDonald's,4.5,27,"Burgers, Beverages, Cafe, Desserts",Kandivali East,75,30
1,KFC,4.2,30,"Burgers, Biryani, American, Snacks, Fast Food",Kandivali East,80,40
2,Domino's Pizza,4.3,25,"Pizzas, Italian, Pastas, Desserts",Thakur Village,299,not_available
3,Charcoal Eats - Biryani & Beyond,4.3,24,"Biryani, Kebabs, Hyderabadi, North Indian",Malad Kan East,100,50
4,Sandwizzaa,4.6,22,"Snacks, Fast Food, Beverages, Jain",Kandivali East,120,60
...,...,...,...,...,...,...,...
1744,Allspice,3.8,48,"North Indian, Chinese, Biryani, Tandoor",Kandivali west,700,20
1745,Poddar Cuisine,4.6,52,"Chinese, Biryani, Beverages",Malad Kan West,not_available,not_available
1746,JUG's Kitchen,4,48,"Indian, Lebanese, Mughlai, Chinese",Goregaon East,999,not_available
1747,Choco Magic Patisserie & Confectioners Studio,4.1,43,"Desserts, Beverages",Malad West,not_available,not_available
1748,Yogita Restaurant,3.9,58,"Indian, Chinese, Tandoor, Seafood",Malad Kan West,not_available,not_available

In [22]:
zomato

,name,online_order,book_table,rate,votes,approx_cost(for two people),listed_in(type)
0,Jalsa,Yes,Yes,4.1/5,775,800,Buffet
1,Spice Elephant,Yes,No,4.1/5,787,800,Buffet
2,San Churro Cafe,Yes,No,3.8/5,918,800,Buffet
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,300,Buffet
4,Grand Village,No,No,3.8/5,166,600,Buffet
...,...,...,...,...,...,...,...
143,Melting Melodies,No,No,3.3/5,0,100,Dining
144,New Indraprasta,No,No,3.3/5,0,150,Dining
145,Anna Kuteera,Yes,No,4.0/5,771,450,Dining
146,Darbar,No,No,3.0/5,98,800,Dining
147,Vijayalakshmi,Yes,No,3.9/5,47,200,Dining